### PR TITLE
rsync_tmbackup.sh:

### PR DESCRIPTION
**Pull request by JohnKaul**
Added the potential feature to have a `.sync/IgnoreList` file for each
`SOURCE_FOLDER` without having to specify `EXCLUDE_FILE` each run.

### CODE REVIEW

**Comment by laurent22** [comment]
I'd be quite keen to merge this, as I think we should indeed move to use flags so that we can add more features more easily. But the fact that we'll break existing scripts is a big issue. I think one ok way to deal with this would be to detect if the parameters *do not* start with a dash - if they don't, we print a warning to stderr with something like "Parameters formatting has been changed in the latest version of rsync_tmbackup. Please update your command line syntax.", and below we print the command usage. Do you think that would work, and would you be ok with adding the feature?

**Comment by musically-ut** [comment]
I would be happy with that route to deprecation. +1

**Comment by JohnKaul** [comment]
I'm not sure it would be the best idea (read: good programming practice), to use a hand-rolled argument parser **and** `getopt`; I think the "best" idea would be to use a hand rolled argument parser instead (although, I think `getopt` is the safer choice). ...I'll try and find some time to mock something up.

**Comment by JohnKaul** [comment]
I'm sorry, I cannot find a good way to implement backwards compatibility for parsing the command line arguments.

**Comment by laurent22** [comment]
For information, I've put the requirements for command line parsing there: https://github.com/laurent22/rsync-time-backup/issues/54

It's a long due feature since its absence means quite a few pull requests couldn't be integrated.

**Comment by laurent22** [comment]
Now that the script supports arguments, are you still interested in having this merged? If so, please update the PR so that it's based on the latest version and I'll merge it.

**Comment by JohnKaul** [comment]
I had an argument parser written in April of 2016 you may want to look over -i.e. your "--" option is not "correct" (-- means to ignore all further arguments) and your default case assumes that any un-flagged arguments to the script are supplied in proper order (very dangerous).

I'm not sure we can merge anymore. I think we got too far off base when I decided to break backwards compatibility with un-flagged arguments. And to be honest, I had at one time started down another path with a program idea (a sort of combination of rsync and unison) I was writing in C++.

**Comment by laurent22** [comment]
Yes I thought about rewriting it too in Golang at some point, but left it like this. The advantage of Bash is that it's just a text file that anybody can easily tweak (or even fix), and most terminal users know Bash.

I will close the PR for now. If you'd like to integrate some of these features please open a new PR.

**Pull request closed without merging**
