### PR TITLE
SSH support added.

### PR DESCRIPTION
**Pull request by fustundag**
Backups can be created at remote server via ssh. Destination folder
should be given like “root@192.168.0.1:/bakcups”

NOTE: Assumed public/private key config is ok.

### CODE REVIEW

**Comment by laurent22** [comment]
I'm curious, is there still some interest in this feature? The initial pull request cannot currently be merged due to the lack of Cygwin compatibility, however if someone is interested in fixing this and getting the feature merged, I'm happy to give you commit access. Please let me know here or by email.

**Comment by thecosmicfrog** [comment]
I'm definitely interested in this being merged with upstream. I'm currently using @fustundag's fork for a lot of my systems, since it's an easy and robust backup option. I couldn't commit to working on this due to the number of projects I'm currently working on though. I also have no experience with developing for Cygwin.

**Comment by fustundag** [comment]
I am trying to merge master with mine. 

I have no experience with cywin. I try to install windows machine with cygwin. If I get any progress, I will keep you informed

**Comment by laurent22** [comment]
I don't have a machine with Cygwin setup at the moment, but normally most things that work in Linux work in Cygwin. The difference might just be how the dates are generated and parsed (and this fix is already in master).

**Comment by fustundag** [comment]
I will create EC2 instance when my merge is completed and I will test quickly.

**Comment by fustundag** [comment]
Test is done: I sent backup files from Cygwin 2.2.1 at Windows Server 2012 R2 64bit to CentOS linux.
More tests are always better :)

**Comment by thecosmicfrog** [comment]
Haha, and @fustundag's changes have broken my Salt states! :D

All for progress!

**Comment by fustundag** [comment]
@thecosmicfrog sorry for broken things. I hope it is not big deal for you :)

Let me know if I can do something.

**Comment by thecosmicfrog** [comment]
@fustundag Haha, not at all. Looks like some indentations may have changed? I have local changes in my repo for some reason. I just did a git checkout -- on rsync_tmbackup.sh and did a fresh pull. Seems to be working again :)

**Comment by fustundag** [comment]
@laurent22 my first commit for this pull request is very old : https://github.com/fustundag/rsync-time-backup/commit/f3a265b07e708ce45cd7ed2d4dd4a86f0ebf39cc

Can you check sh file from my repo master?

I ported  "pid >> in progress file" and "pgrep appname" fixes.

Is there any fix needed to port?

**Comment by laurent22** [comment]
@fustundag, the reason it wasn't working for me is that I was testing on Cygwin, and apparently neither solution works in this env. Process names for Bash scripts only show up as "/usr/bin/bash" so it's not straightforward to detect if it's already running. I will merge the pull request and add a TODO for Cygwin.

**Comment by laurent22** [comment]
Okay, *finally* the feature is merged :+1: Thanks a lot for your work!

**Comment by fustundag** [comment]
@laurent22 Ok, I will test with cygwin.

**Pull request merged**
