### PR TITLE
do not search for directories recurisve

### PR DESCRIPTION
**Pull request by SimonHeimberg**
This gives a big speed improvement when the dest dir contains other directories containting many subdirectories.

### CODE REVIEW

**Comment by SimonHeimberg** [comment]
The 2nd commit could be squashed.

**Comment by laurent22** [comment]
Yes I think that's a good change, I just need to test it to confirm and I'll merge.

**Comment by markussc** [comment]
Nice one, confirm it works perfectly!

**Comment by laurent22** [comment]
`-maxdepth=1` doesn't work for me neither on Cygwin nor WSL, however `-maxdepth 1` works. Please could you check that it works for your too and update the pull request with it?

**Comment by SimonHeimberg** [comment]
oops, sorry. With `=` it did not work on linux either. I failed to type what I have tried.

The 3 commits can be squashed. I can rebase and force push if demanded.

**Comment by laurent22** [comment]
Thanks, that looks good now.

**Pull request merged**
