### PR TITLE
display usage info if required args not passed

### PR DESCRIPTION
**Pull request by bhuvi8**
Added a function to display usage information, when the required arguments are not passed as input, instead of just assigning spaces to source and destination folder and displaying irrelevant error message.

### CODE REVIEW

**Comment by lorentrogers** [comment]
+1 on this. Seems like a good default function.

**Comment by laurent22** [comment]
Not sure why I missed this pull request as it looks like a useful change. It currently cannot be merged though, but if @bhuvi8 or someone else could fix it I'd be glad to include the feature.

**Comment by bhuvi8** [comment]
rebased code to master

**Comment by laurent22** [comment]
The display_usage feature is nice to have, but I'd rather not make any assumption about the default dir (rsync doesn't either). If you could remove this part, I'd be happy to merge it.

**Comment by bhuvi8** [comment]
It now doesn't assume about destination if not provided.

**Comment by laurent22** [comment]
This is great, thanks a lot!

**Pull request merged**
