### PR TITLE
prevent execution of concurrent backup tasks

### PR DESCRIPTION
**Pull request by eaut**
Do not start new backups if a backup is already ongoing

This should prevent the following scenario:
1) cron starts backup
2) computer goes into sleep/hibernate mode while backup process is still running
3) computer wakes up and the backup continues
4) with bad timing cron starts a second backup while the old backup is still not finished

### CODE REVIEW

**Comment by laurent22** [comment]
Very good, thanks for the pull request. I'm going to check on Linux Mint, but any idea if it works on OS X as well?

**Comment by eaut** [comment]
works on Ubuntu, should work on OSX too if you change the pgrep argument from --pidfile to -F

**Comment by laurent22** [comment]
Hmm... I'm just thinking:

- What happens if the script is interrupted with Ctrl+C? In this case, I think the file will remain with the PID inside and will block any attempt to restart the backup. Or am I missing something?

- Is there any way to be completely POSIX compliant? That way, we'd keep compatibility with Cygwin and OS X. What do you think?

**Comment by eaut** [comment]
The "if pgrep" condition will only be true as long as the process that created $INPROGRESS_FILE is still running. In all other cases the there is no change to the original behavior.

**Comment by eaut** [comment]
I messed this pull-request seriously up, I'll send you a new one

**Pull request closed without merging**
